language: ruby
before_install:
  - sudo apt-get install wget
  - wget http://owl.phy.queensu.ca/~phil/exiftool/Image-ExifTool-11.30.tar.gz
  - tar -xzf Image-ExifTool-11.30.tar.gz
  - cd Image-ExifTool-11.30
  - perl Makefile.PL
  - make
  - sudo make install
  - cd ..
  - exiftool -ver
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
notifications:
  email:
    - janfri26@gmail.com
